[workspace]
members = ["rlp", "types", "fuzz"]
default_member = "rlp"
resolver = "2"

[workspace.dependencies]
rlp-rs = { path = "./rlp" }
serde_bytes = "0.11.15"
serde = { version = "1.0.204", features = ["derive"] }
libfuzzer-sys = "0.4"

[profile.bench]
debug = true
