[package]
name = "rlp-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1.0.15"
serde = { workspace = true }
serde_bytes = { workspace = true }

[dev-dependencies]
serde_repr = "0.1.19"
